services:
  backend:
    build: ./mysite
    ports:
      - "8000:8000"
    volumes:
      - ./mysite/.pg_service.conf:/home/appuser/.pg_service.conf
      - ./mysite/.pgpass:/app/.pgpass
    env_file:
      - .env
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mysite
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
    ports:
      - "5432:5432"
