services:
  backend:
    build: ./mysite
    ports:
      - "8000:8000"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mysite
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
    ports:
      - "5432:5432"
